Source/com/drew/metadata/gif/GifHeaderDirectory.java
Source/com/drew/metadata/gif/GifReader.java
Tests/com/drew/metadata/gif/GifReaderTest.java

GifHeaderDirectory class has TAG_TRANSPARENT_COLOR_INDEX tag, but its value is read from the Background Color Index field in the GIF header. The tag name should be TAG_BACKGROUND_COLOR_INDEX. This closes #141.

Change GifHeaderDirectory.TAG_TRANSPARENT_COLOR_INDEX to TAG_BACKGROUND_COLOR_INDEX

---

Source/com/drew/metadata/jfif/JfifDirectory.java

Add getResY() and getResX(), and mark getImageWidth() and getImageHeight() as deprecated. This closes #143

Rename JfifDirectory.getImageWidth() and JfifDirectory.getImageHeight()

---

Source/com/drew/imaging/png/PngMetadataReader.java
Source/com/drew/metadata/icc/IccReader.java
Tests/com/drew/imaging/png/PngMetadataReaderTest.java

Reset TimeInMillis for Calender objects before setting the values, and added a test. This closes #145.

Reset TimeInMillis for Calendar objects before setting the values

---

Source/com/drew/imaging/png/PngMetadataReader.java
Source/com/drew/metadata/Directory.java
Source/com/drew/metadata/icc/IccReader.java
Source/com/drew/metadata/xmp/XmpReader.java
Tests/com/drew/imaging/png/PngMetadataReaderTest.java
Tests/com/drew/metadata/DirectoryTest.java
Tests/com/drew/metadata/icc/IccReaderTest.java
Tests/com/drew/metadata/xmp/XmpReaderTest.java

* The values for the following tags are now stored as date strings instead of Date objects
* `IccDirectory.TAG_PROFILE_DATETIME`
* `PngDirectory.TAG_LAST_MODIFICATION_TIME`
* `XmpDirectory.TAG_DATETIME_ORIGINAL`
* `XmpDirectory.TAG_DATETIME_DIGITIZED`
* Modified the `Directory.getDate()` method so that it can parse a date string in the ISO 8601 format for the XMP tags
* Added many date parsing tests

Improved timestamp handling

---

Source/com/drew/metadata/exif/GpsDescriptor.java
Source/com/drew/metadata/exif/GpsDirectory.java
Tests/com/drew/metadata/exif/ExifDirectoryTest.java

* Added `GpsDirectory.getGpsDate()` that parses the date stamp tag and the time stamp tag and returns a single `Date` object
* Modified the `GpsDescriptor.getGpsTimeStampDescription()` to return up to third decimal place
* Added tests that parse geo location data and gps date/time data

Added the getGpsDate() method

---

Source/com/drew/metadata/iptc/IptcDescriptor.java
Source/com/drew/metadata/iptc/IptcDirectory.java
Source/com/drew/metadata/iptc/IptcReader.java
Tests/com/drew/metadata/iptc/IptcDirectoryTest.java
Tests/com/drew/metadata/iptc/IptcReaderTest.java

* Added the `getXxxDate()` methods that parse the date tag and the time tag and return a single `Date` object
* Added the `getXxxDateDescription()` and `getXxxTimeDescription()` methods that return a descriptive string representation of the date and time
* Removed the date parsing code from `IptcReader`, and all the values for the date and time tags are now stored as strings instead of `Date` objects
* Added several date parsing tests

Added date parsing methods to IptcDirectory

---

Source/com/drew/imaging/jpeg/JpegSegmentReader.java

When an incorrect jpeg segment length is specified, try to recover by scanning for the next segment marker rather than bailing out with an exception.

Fix for issue #121

---

Source/com/drew/metadata/exif/ExifDirectoryBase.java
Source/com/drew/metadata/exif/ExifTiffHandler.java

Ported from drewnoakes/metadata-extractor-dotnet#40 - addresses the other half of #151
IFD0 was missing the ApplicationNotes tag (0x02BC) which can apparently hold XMP data. This assumes it is always XMP in there, but I can't 100% confirm this.

Handle Tiff IFD0 ApplicationNotes tag (0x02bc) as XMP

---

Source/com/drew/metadata/exif/GpsDirectory.java

- Fixed formatting of the dateTime to be locale independent
GitHub Issue #160

Make GpsDirectory#getGpsDate() locale independent

---

Tests/com/drew/imaging/png/PngMetadataReaderTest.java

- formatting is done in the US locale to match the expected result in
the platform/locale independent manner
GitHub Issue #162

Make PngMetadataReaderTest locale independent

---

Source/com/drew/metadata/iptc/IptcReader.java

Fixes an issue where a single-byte value at the end of an IPTC directory
would not be sufficient to consider the number of remaining bytes
sufficient, causing the extraction to be halted prematurely.

IPTC metadata: Fix an off-by-one error.

---

Source/com/drew/lang/Charsets.java
Source/com/drew/metadata/exif/ExifTiffHandler.java
Source/com/drew/metadata/exif/makernotes/ReconyxHyperFireMakernoteDescriptor.java
Source/com/drew/metadata/exif/makernotes/ReconyxHyperFireMakernoteDirectory.java
Source/com/drew/metadata/exif/makernotes/ReconyxUltraFireMakernoteDescriptor.java
Source/com/drew/metadata/exif/makernotes/ReconyxUltraFireMakernoteDirectory.java

Port of .NET commit drewnoakes/metadata-extractor-dotnet@1542a7d
This is complete for Hyper, but incomplete for Ultra; none of the DirectoryExtensions or ByteConvert changes were ported. Some of the obvious Ultra tags are implemented, but I don't have a test image to finish it off. Maybe @twest820 is interested in finishing it.

support Reconyx Hyper and UltraFire makernotes

---

Source/com/drew/imaging/png/PngMetadataReader.java
Source/com/drew/metadata/exif/ExifDescriptorBase.java
Source/com/drew/metadata/exif/ExifDirectoryBase.java
Source/com/drew/metadata/exif/ExifImageDescriptor.java
Source/com/drew/metadata/exif/ExifImageDirectory.java
Source/com/drew/metadata/exif/ExifTiffHandler.java
Source/com/drew/metadata/jpeg/JpegReader.java

Ports from .NET:
- drewnoakes/metadata-extractor-dotnet@6752a7d
- drewnoakes/metadata-extractor-dotnet@c9693ed
- drewnoakes/metadata-extractor-dotnet@a15147b
There is an InflaterInputStream change that should be reviewed. It's documented in the code.
PNG zTXt seems to work with what's in the image repo, but eyes peeled in the future.
KeyValuePair was implemented differently in Java - the 'key' was a StringValue. This change makes it match .NET where the key is a string. A StringValue doesn't really give us any advantages as a key (I think).

PNG zTXt, ExifImage directory, multipage TIFF

---

Source/com/drew/imaging/jpeg/JpegMetadataReader.java
Source/com/drew/imaging/jpeg/JpegSegmentType.java
Source/com/drew/metadata/jpeg/HuffmanTablesDirectory.java
Source/com/drew/metadata/jpeg/JpegDhtReader.java
Source/com/drew/metadata/jpeg/JpegDnlReader.java
Tests/com/drew/metadata/jpeg/HuffmanTablesDirectoryTest.java

I realized I'd made a couple of mistakes in #231:
* I didn't take into account the stuffing bytes (x00 following a xFF) when reading Huffman tables.
* The requirement for ```isTypical()``` that there had to be 4 Huffman tables is invalid for progressive JPEGs.
I added support for stuffing bytes in ```JpegDhtReader```. I still haven't seen this being used in a Huffman table in any of my tests which is why I didn't think of it earlier.
The requirement for 4 Huffman tables became evident that was wrong when the progressive JPEGs came up - my initial idea was that there the typical tables are 4, thus require the total number to be 4. I still think this might technically be a correct requirement even for progressive, as I can't see why they would need to redefine any of the already defined …

Small update/follow up to #231

---

Source/com/drew/metadata/jpeg/JpegComponent.java
Source/com/drew/metadata/jpeg/JpegDescriptor.java

This is really minor, but every time I run a test against the images repo, I get a diff on ```eddea4ef9629be031f750a8ff0b7497c.jpg``` because ```JpegComponent``` is printed in the form ```com.drew.metadata.jpeg.JpegComponent@25586e1e```. The array address is always different for obvious reasons, and thus the diff. 
By moving the "textual representation generation" to ```JpegComponent.toString()``` it will work in this instance as well, eliminating that pesky diff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/drewnoakes/metadata-extractor/235)

Move JpegComponent description

---

Source/com/drew/metadata/jpeg/JpegDhtReader.java

I made a serious error in e9daa3df94e820af8885f78f3404ef8d814f59d5. I must admit that I didn't know that Java defined byte as "signed" - to me that is such a strange concept that I've never even considered it. I've seen the negative "byte" values in the debugger, but I've assumed it was simply a display issue.
It seems ```short``` is the way to go when comparing "byte" values in Java, but I've kept it as a byte here since it's being put into a byte array after comparison. I've run regressions tests and there is no diff, as this code only makes a difference if a Huffman table entry has a ```xFF``` value - which I haven't seen yet.

Fix "signed byte" bug introduced in #234

---

Source/com/drew/metadata/gif/GifControlDirectory.java
Source/com/drew/metadata/gif/GifReader.java

I need to check if GIF's have transparency or not, and found that the key to this is in the "Graphics Control Extension". The flag I need isn't parsed though, so I implemented parsing of the rest of the information found in this block.
I've run it against the "images" repo, and the results look reasonable.

Full parsing of GIF Graphics Control Extension

---

Source/com/drew/metadata/jpeg/JpegDhtReader.java

This fixes the bug reported in #242. I've tested it against the [submitted image](https://cloud.githubusercontent.com/assets/8233283/22927412/14b497d2-f2ec-11e6-80ea-605318beaa16.jpg) and it now parses correctly. I've also tested it with no diffs against the images repository.
I'm really sorry for this, I've looked through it and I can't see any more of these now. It's extra bad that a release took place with this bug in it.

Fix another "signed byte" bug introduced in #234

---

Source/com/drew/imaging/FileTypeDetector.java
Source/com/drew/lang/Charsets.java
Source/com/drew/metadata/bmp/BmpHeaderDescriptor.java
Source/com/drew/metadata/bmp/BmpHeaderDirectory.java
Source/com/drew/metadata/bmp/BmpReader.java

While testing I found some BMP's that couldn't be parsed. This lead me to thing that it was such an easy file format that I could quickly extend it to cover "everything". I was wrong. This wasn't quick at all, but I think I've covered most of the BMP variants now.
I have some things I'm unsure about. First of all, I've put some ```formatHex()``` and ```formatFixed1616()``` in ```BmpHeaderDescriptor```. They are too general to be there, but I couldn't find where such methods are kept. Please advise.
As usual I'm also unsure about the formatting, line wrapping etc. I've done my best to try to keep the existing style, but please let me know if anything should be changed.
I had to add ```WINDOWS-1252``` to ```Charsets``` because BMP files use this character set by definition. I don't know if …

Extend BMP support

---

Source/com/drew/metadata/gif/GifReader.java

This pr fixes cast of unsigned value of 255 to signed -1 when reading length of ICC profile in GIF blocks.

BugFix - convert to unsigned value.

---

Source/com/drew/metadata/gif/GifReader.java

To read whether a GIF file has Global Color Table, we have to check the most significant bit in 5th byte of Logical Screen Descriptor. Reference:- https://www.w3.org/Graphics/GIF/spec-gif89a.txt and http://www.martinreddy.net/gfx/2d/GIF87a.txt. But this looks like incorrectly calculated, instead of checking the 8th bit, this checks first four bits.
Although, I find it perplexing that if hasGlobalColorTable was incorrectly read, a skip of X bytes should have led to some major issues which would have led to catching of this bug early on. Could you comment on this? Thank you.

BugFix - rectify read of Global & Local Color Table presence in GIF

---

Source/com/drew/imaging/FileTypeDetector.java

Quick fix on the NEF file signature in FileTypeDetector... (It was previously identified as Tiff)
Previously: "MM".getBytes(), new byte[]{0x00, 0x2a, 0x00, 0x00, 0x00, (byte)**0x80**, 0x00}
Now: "MM".getBytes(), new byte[]{0x00, 0x2a, 0x00, 0x00, 0x00, (byte)**0x08**, 0x00}
Sources: 
http://filext.com/file-extension/NEF
http://lclevy.free.fr/nef/

Fix NEF file signature

---

Source/com/drew/imaging/FileType.java
Source/com/drew/imaging/FileTypeDetector.java
Source/com/drew/imaging/ImageMetadataReader.java
Source/com/drew/metadata/file/FileMetadataDirectory.java
Source/com/drew/metadata/file/FileMetadataReader.java

This is something that our organization would find useful in the library as it expands.  It would be nice to have file detection for some file formats like those using the zip container even if there isn't any metadata associated with it just yet.  
I have simply added to the FileType enum class to allow a File Type String and MIME Type String to be stored.  This data is then stored in the File Metadata Directory.
If this isn't something you would like in the library, no big deal.  I figured I would throw it out there, though!

Add 'File Type' and 'MIME Type' to enum and container/content handling

---

Source/com/drew/metadata/mov/QuickTimeDescriptor.java
Source/com/drew/metadata/mov/atoms/MovieHeaderAtom.java
Source/com/drew/metadata/mov/atoms/VideoInformationMediaHeaderAtom.java
Source/com/drew/metadata/mov/media/QuickTimeVideoDescriptor.java
Source/com/drew/metadata/mp4/Mp4Descriptor.java
Source/com/drew/metadata/mp4/boxes/MovieHeaderBox.java
Source/com/drew/metadata/mp4/boxes/VideoMediaHeaderBox.java
Source/com/drew/metadata/mp4/media/Mp4VideoDescriptor.java

Fixes TODO about Graphics Mode raw data storage from c74bc8311509b and adds null value checking for MP4 and QuickTime descriptors.  Also moves duration raw number storage to directory and puts the duration calculation in the descriptor.

Fix raw number storage TODO, add null value checking for MP4/QT, and fix duration raw number storage

---

Source/com/drew/metadata/eps/EpsReader.java
Source/com/drew/metadata/photoshop/PhotoshopTiffHandler.java

Prevents the EPS reader from commonly throwing IOExceptions by stopping the reader at the first non-comment line similar to Exif Tool.  Also implement PhotoshopTiffHandler for photoshop-specific tiff tags used in the EPS reader.

Stop EPS reader at first non-comment line and add PhotoshopTiffHandler for Photoshop-specific tags

---

Source/com/drew/metadata/exif/ExifTiffHandler.java

Hi,
As discussed separately in https://github.com/drewnoakes/metadata-extractor-images/pull/17#issuecomment-338025641
An out of bound error was triggered by certain JPEGs, such as the ones produced
by Blackberry 10 phones. This was traced to the way the makernote is parsed,
where many strings of increasing length are obtained from the file. In the
above case length 12 was causing the unecessary failure.
This patch replaces the failure with an empty string, which preserves the logic
but suppresses the failure, allowing the metadata parsing to proceed nicely.

ExifTiffHandler: correct out of bound error

---

Source/com/drew/metadata/mov/atoms/MovieHeaderAtom.java
Source/com/drew/metadata/mp4/boxes/MovieHeaderBox.java

Fixes #303 
Since QuickTime files (including MP4), use the reference time of January 1, 1904, the date must be calculated differently than others.  Previously, the date object was created and then toString was called to store it in the directory.  I have opted to just store the date itself since we create it anyways.  This will solve the issue since Directory's getDate will return at line 867 if the object is already an instance of java.util.Date.

Store date instead of string for creation/modification time

---

Source/com/drew/imaging/mp4/Mp4Reader.java
Source/com/drew/metadata/mp4/boxes/Box.java

Fixes #306 
Added correct handling of UUID atoms in Mp4Reader.
Reader was not skipping the extra 16 bytes before the payload that is the actual UUID.

Account for extra 16 bytes in UUID atoms

---

Source/com/drew/metadata/mp4/Mp4Directory.java
Source/com/drew/metadata/mp4/boxes/MovieHeaderBox.java

This changes add a new tag `TAG_DURATION_SECONDS` to `Mp4Directory`.
The property that corresponds to the tag is video duration in seconds, stored as `Rational` whose numerator and denominator are the corresponding property of `TAG_DURATION` and `TAG_TIME_SCALE` respectively.
This PR resolves the issue #312 .

Add a tag for duration in seconds to mp4 directory

---

Source/com/drew/metadata/png/PngDescriptor.java
Tests/com/drew/metadata/png/PngDescriptorTest.java

`PngDescriptor.getBackgroundColorDescription()` always returns null even if `TAG_BACKGROUND_COLOR` has some value. This is because the code checks the `TAG_COLOR_TYPE` value, but it exists in the different directory (PNG-IHDR).
Return the description based on the length of the byte array. I also added a few tests for `PngDescriptor`.

Fix null return from PngDescriptor.getBackgroundColorDescription()

---

Source/com/drew/metadata/xmp/XmpDirectory.java
Tests/com/drew/metadata/xmp/XmpReaderTest.java

`XmpDirectory.getXmpProperties` returns a map of XMP properties, but it includes array and struct parent properties which don't have an actual value. I suggest that it is preferable to exclude them from the map.
Example:
```
...
"Iptc4xmpCore:CountryCode": "DE"
"Iptc4xmpCore:Location": "Fotostudio HS"
"Iptc4xmpCore:CreatorContactInfo": ""           <-- Struct parent node
"Iptc4xmpCore:CreatorContactInfo/Iptc4xmpCore:CiAdrCity": "Mainz"
"Iptc4xmpCore:CreatorContactInfo/Iptc4xmpCore:CiAdrCtry": "Deutschland"
"Iptc4xmpCore:CreatorContactInfo/Iptc4xmpCore:CiAdrExtadr": "Konrad-Adenauer-Str. 33"
"Iptc4xmpCore:CreatorContactInfo/Iptc4xmpCore:CiAdrPcode": "55129"
"Iptc4xmpCore:CreatorContactInfo/Iptc4xmpCore:CiAdrRegion": "Rheinland-Pfalz" …
```

Remove XMP array and struct parent properties

---

Source/com/drew/metadata/mov/QuickTimeDescriptor.java
Source/com/drew/metadata/mov/atoms/SoundSampleDescriptionAtom.java
Source/com/drew/metadata/mov/atoms/TimeToSampleAtom.java
Source/com/drew/metadata/mov/atoms/VideoSampleDescriptionAtom.java
Source/com/drew/metadata/mov/media/QuickTimeVideoDescriptor.java
Source/com/drew/metadata/mp4/Mp4Descriptor.java
Source/com/drew/metadata/mp4/boxes/AudioSampleEntry.java
Source/com/drew/metadata/mp4/boxes/VisualSampleEntry.java
Source/com/drew/metadata/mp4/media/Mp4SoundDirectory.java
Source/com/drew/metadata/mp4/media/Mp4VideoDescriptor.java
Source/com/drew/metadata/mp4/media/Mp4VideoDirectory.java

I noticed a few issues of MOV and MP4 parsing.
```
[QuickTime] Major Brand = Apple QuickTime (.MOV/QT)
[QuickTime] Minor Version = 512
[QuickTime] Compatible Brands = [Apple QuickTime (.MOV/QT)]
[QuickTime] Creation Time = Fri Jan 01 00:00:00 +06:55 1904
[QuickTime] Modification Time = Fri Jan 01 00:00:00 +06:55 1904
[QuickTime] Duration = 01:32:3650                                  <-- Problem 1
[QuickTime] Media Time Scale = 1000
[QuickTime] Duration in Seconds = 5.57
[QuickTime] Preferred Rate = 1
[QuickTime] Preferred Volume = 1
[QuickTime] Preview Time = 0
[QuickTime] Preview Duration = 0
[QuickTime] Poster Time = 0
[QuickTime] Selection Time = 0
[QuickTime] Selection Duration = 0
[QuickTime] Current Time = 0
[QuickTime] Next Track ID = 3
ERROR: End of data reached.
[QuickTime Video] …
```

Fix MOV/MP4 parsing issues

---

Source/com/drew/metadata/exif/GpsDescriptor.java
Source/com/drew/metadata/exif/GpsDirectory.java

- Add `TAG_H_POSITIONING_ERROR` (0x001F), which was added in the Exif 2.3 specification
- Add a description for `TAG_DOP` providing a decimal version of rational numbers
- Add a description for `TAG_SPEED` providing a decimal version of rational numbers with unit
- Add a description for `TAG_DEST_LATITUDE` providing a DMS representation of rational numbers with unit
- Add a description for `TAG_DEST_LONGITUDE` providing a DMS representation of rational numbers with unit
- Add a description for `TAG_DEST_DISTANCE` providing a decimal version of rational numbers with unit
- Add a description for `TAG_PROCESSING_METHOD` and `TAG_AREA_INFORMATION` providing a string representation using the character code stored in the first 8 bytes of the byte array
- Add a description for …

Exif GPS directory and descriptor updates

---

Source/com/drew/imaging/FileType.java
Source/com/drew/imaging/FileTypeDetector.java
Source/com/drew/imaging/ImageMetadataReader.java
Source/com/drew/imaging/mp3/Mp3MetadataReader.java
Source/com/drew/imaging/mp3/package-info.java
Source/com/drew/metadata/mp3/Mp3Descriptor.java
Source/com/drew/metadata/mp3/Mp3Directory.java
Source/com/drew/metadata/mp3/Mp3Reader.java
Source/com/drew/metadata/mp3/package-info.java

This is a very basic implementation for MP3 support under the assumption that no ID3 block is present at the beginning of the file. As a result of this assumption, many MP3 files will not yet be recognized as it is very common for an ID3 block to be present.
I opted to still create this PR to kick start development of MP3.
File identification is based off of the first frame header in the file, which has this structure
http://mpgedit.org/mpgedit/mpeg_format/MP3Format.html
* It is only guaranteed that the first 11 bits are set, so I only check that the file starts with 0xFF as the signature. One option is to add the remaining combinations (MPEG1 + Layer2, MPEG2 + Layer2, etc) to filetypedetector, but that would be cumbersome.
* Some MPEG files use bitrate switching, which means the first …

Implement basic support for MP3 files without ID3

---

Source/com/drew/metadata/exif/makernotes/OlympusRawDevelopment2MakernoteDescriptor.java

Olympus cameras with the "Auto" noise reduction setting  (bit 3 set) causes this code to crash with an IndexOutOfBoundsException.
I've now added support for bit 3 ("Auto") and made the code fault tolerant if future bits are added.
Reference: https://sno.phy.queensu.ca/~phil/exiftool/TagNames/Olympus.html
I add a sample image so you can reproduce the bug and verify the fix I made too.

Fix for "Auto" noise reduction setting

---

Source/com/drew/metadata/icc/IccDirectory.java

This adds several private ICC tags, which are registered by Apple Inc.
Reference: http://www.color.org/registry/signature/TagRegistry-2018-03.pdf

Add several private ICC tags

---

Source/com/drew/imaging/ImageMetadataReader.java

The current implementation only shows the XMP Value Count, but this fix lists all of XMP properties as well.
```
$ java -cp xmpcore-5.1.3.jar:metadata-extractor-2.11.1-SNAPSHOT.jar com.drew.imaging.ImageMetadataReader rose-128x174-24bit-lzw.tiff
...
[Exif IFD0] Predictor = 2
[Exif IFD0] Unknown tag (0x8649) = [5390 values]
[Exif IFD0] Inter Color Profile = [3144 values]
[XMP] XMP Value Count = 21
[XMP] xmp:ModifyDate = 2016-02-05T01:25:42+09:00
[XMP] xmp:MetadataDate = 2016-02-05T01:25:42+09:00
[XMP] xmp:CreatorTool = Adobe Photoshop CS2 Windows
[XMP] photoshop:History = 
[XMP] photoshop:ICCProfile = sRGB IEC61966-2.1
[XMP] tiff:XResolution = 720090/10000
[XMP] xmpMM:DerivedFrom/stRef:documentID = uuid:755EFE1B5BCBE51191D2BA1A4A34CC1F
[XMP] tiff:NativeDigest = …
```

Show XMP tags in ImageMetadataReader main method

---

Source/com/drew/metadata/exif/ExifDirectoryBase.java
Source/com/drew/metadata/exif/ExifTiffHandler.java

The Photoshop settings (tag 0x8649) and ICC Profile (tag 0x8773) embedded in IFD0 of TIFF files are not extracted into directories. For example:
```
[Exif IFD0] New Subfile Type = Full-resolution image
[Exif IFD0] Image Width = 128 pixels
[Exif IFD0] Image Height = 174 pixels
[Exif IFD0] Bits Per Sample = 8 8 8 bits/component/pixel
[Exif IFD0] Compression = LZW
[Exif IFD0] Photometric Interpretation = RGB
[Exif IFD0] Strip Offsets = 23876
[Exif IFD0] Orientation = Top, left side (Horizontal / normal)
[Exif IFD0] Samples Per Pixel = 3 samples/pixel
[Exif IFD0] Rows Per Strip = 174 rows/strip
[Exif IFD0] Strip Byte Counts = 26556 bytes
[Exif IFD0] X Resolution = 72009/1000 dots per inch
[Exif IFD0] Y Resolution = 72009/1000 dots per inch
[Exif IFD0] Planar Configuration = Chunky (contiguous …
```

Support extraction of ICC Profile and Photoshop settings embedded in IFD0 of TIFF file

---

Source/com/drew/metadata/exif/ExifDescriptorBase.java
Source/com/drew/metadata/exif/ExifDirectoryBase.java
Source/com/drew/metadata/exif/ExifSubIFDDirectory.java

- Add the following tags defined in [the Exif Version 2.31 specification](http://www.cipa.jp/std/documents/e/DC-008-Translation-2016-E.pdf):
- `TAG_ISO_SPEED` (0x8833)
- `TAG_ISO_SPEED_LATITUDE_YYY` (0x8834)
- `TAG_ISO_SPEED_LATITUDE_ZZZ` (0x8835)
- `TAG_OFFSET_TIME` (0x9010)
- `TAG_OFFSET_TIME_ORIGINAL` (0x9011)
- `TAG_OFFSET_TIME_DIGITIZED` (0x9012)
- `TAG_TEMPERATURE` (0x9400)
- `TAG_HUMIDITY` (0x9401)
- `TAG_PRESSURE` (0x9402)
- `TAG_WATER_DEPTH` (0x9403)
- `TAG_ACCELERATION` (0x9404)
- `TAG_CAMERA_ELEVATION_ANGLE` (0x9405)
- Add the following description methods:
- `ExifDescriptorBase.getBrightnessValueDescription()`
- `ExifDescriptorBase.getTemperatureDescription()`
- `ExifDescriptorBase.getHumidityDescription()`
- `ExifDescriptorBase.getPressureDescription()`
- …

Add Exif 2.31 tags

---

Source/com/drew/metadata/exif/ExifSubIFDDirectory.java
Tests/com/drew/metadata/exif/ExifDirectoryTest.java

This is an extension of #158.
- Add the following new methods to get composite values from `TAG_DATETIME`, `TAG_SUBSECOND_TIME` and `TAG_OFFSET_TIME`  tags
- `ExifSubIFDDirectory.getDateModified()`
- `ExifSubIFDDirectory.getDateModified(TimeZone timeZone)`
- Add `ExifSubIFDDirectory.getTimeZone()` common method
- Add corresponding tests

Add getDateModified() methods to get composite values from multiple Exif tags

---

Source/com/drew/lang/ByteUtil.java
Tests/com/drew/lang/ByteUtilTest.java

While [running FindBugs on latest master per @kwhopper's request ](https://github.com/drewnoakes/metadata-extractor/issues/364#issuecomment-423224829), some warnings unrelated to locale/encoding popped up that I just couldn't ignore.
The reason this code will fail as it is, is that Java defines everything as `int` (32 bit) by default. As a result, the bits would be "shifted out" and disappear. This should fix it.

Fix bit shifting bug

---

Source/com/drew/metadata/exif/makernotes/NikonType2MakernoteDescriptor.java

With help from Exiftool sources - this value isn't a unix-style int64. The bytes directly describe the date and time.

Fix NikonType2 getPowerUpTimeDescription

---

Source/com/drew/metadata/gif/GifReader.java

I've made `GitReader` ignore too short XMP blocks instead of failing with a `NegativeArraySizeException`. This fixes #351.
Below is the diff from processing the image database before and after this PR with https://github.com/drewnoakes/metadata-extractor-images/pull/23 included:
```diff
gif/metadata/pbar-ani-invalid-XMP.gif.txt | 370 +++++++++++++++++++++++++++++-
1 file changed, 369 insertions(+), 1 deletion(-)
diff --git a/gif/metadata/pbar-ani-invalid-XMP.gif.txt b/gif/metadata/pbar-ani-invalid-XMP.gif.txt
index db6aea5..3aafc7d 100644
--- a/gif/metadata/pbar-ani-invalid-XMP.gif.txt
+++ b/gif/metadata/pbar-ani-invalid-XMP.gif.txt
@@ -1,7 +1,375 @@
FILE: pbar-ani-invalid-XMP.gif
TYPE: GIF
-EXCEPTION: null
+[GIF Header - 0x0001] GIF Format Version = 89a
+[GIF Header - 0x0002] Image Width …
```

Ignore invalid GIF XMP blocks

---

Source/com/drew/metadata/exif/ExifDescriptorBase.java

For the case mentioned in #354
The case when the value is 0x10 - the description should say no Auto - as it is enforced to be OFF

Fix of the Flash description for Flash == OFF

---

Source/com/drew/metadata/heif/boxes/HandlerBox.java
Source/com/drew/metadata/heif/boxes/ItemInfoBox.java

Closes #362 
As per ISO documentation (in class comments), the modified fields are supposed to be null terminated and/or specify the UTF-8 charset.

Fix null terminator and charset issues in heif implementation

---

Source/com/drew/metadata/xmp/XmpDirectory.java
Source/com/drew/metadata/xmp/XmpReader.java
Source/com/drew/metadata/xmp/XmpWriter.java
Source/com/drew/tools/ProcessAllImagesInFolderUtility.java
pom.xml

This updates `com.adobe.xmp:xmpcore` to 6.0.6. It's required for fixing extremely slow parsing when `photoshop:DocumentAncestors` node reaches over 100000 items. I will send the fix in another PR.

Update xmpcore to 6.0.6

---

Source/com/drew/metadata/mp4/boxes/TimeToSampleBox.java

Fixes #386 
After fix, new frame rates as shown below (with sample file provided in corresponding issue):
| Metadata-Extractor        | VLC           | Exiftool  | ffmpeg |
| :-------------: |:-------------:| :-----:|:--------:|
| 30.051      | 30.050836 | 30.051 | 30.05 |
All frame rates in metadata-extractor-images remain the same.

Fix frame rate calculation using handler duration

---

Source/com/drew/metadata/TagDescriptor.java
Source/com/drew/metadata/exif/ExifDescriptorBase.java
Source/com/drew/metadata/exif/PanasonicRawDistortionDescriptor.java
Source/com/drew/metadata/exif/PanasonicRawWbInfo2Descriptor.java
Source/com/drew/metadata/exif/PanasonicRawWbInfoDescriptor.java

Fix stack overflow

---

pom.xml

Without this on Java 11 results in ...
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.1.0:jar (attach-javadocs) on project metadata-extractor: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in https://docs.oracle.com/javase/6/docs/api/ are in the unnamed module.

for compiling with java 11 or greater

---

Source/com/drew/imaging/mp4/Mp4Handler.java
Source/com/drew/imaging/mp4/Mp4Reader.java
Source/com/drew/imaging/quicktime/QuickTimeHandler.java
Source/com/drew/imaging/quicktime/QuickTimeReader.java
Source/com/drew/metadata/mov/QuickTimeAtomHandler.java
Source/com/drew/metadata/mov/QuickTimeContext.java
Source/com/drew/metadata/mov/QuickTimeHandlerFactory.java
Source/com/drew/metadata/mov/QuickTimeMediaHandler.java
Source/com/drew/metadata/mov/QuickTimeMetadataHandler.java
Source/com/drew/metadata/mov/atoms/MediaHeaderAtom.java
Source/com/drew/metadata/mov/atoms/TimeToSampleAtom.java
Source/com/drew/metadata/mov/media/QuickTimeMusicHandler.java
Source/com/drew/metadata/mov/media/QuickTimeSoundHandler.java
Source/com/drew/metadata/mov/media/QuickTimeSubtitleHandler.java
Source/com/drew/metadata/mov/media/QuickTimeTextHandler.java
Source/com/drew/metadata/mov/media/QuickTimeTimecodeHandler.java
Source/com/drew/metadata/mov/media/QuickTimeVideoHandler.java
Source/com/drew/metadata/mov/metadata/QuickTimeDataHandler.java
Source/com/drew/metadata/mov/metadata/QuickTimeDirectoryHandler.java
Source/com/drew/metadata/mp4/Mp4BoxHandler.java
Source/com/drew/metadata/mp4/Mp4Context.java
Source/com/drew/metadata/mp4/Mp4HandlerFactory.java
Source/com/drew/metadata/mp4/Mp4MediaHandler.java
Source/com/drew/metadata/mp4/boxes/MediaHeaderBox.java
Source/com/drew/metadata/mp4/boxes/TimeToSampleBox.java
Source/com/drew/metadata/mp4/media/Mp4HintHandler.java
Source/com/drew/metadata/mp4/media/Mp4MetaHandler.java
Source/com/drew/metadata/mp4/media/Mp4SoundHandler.java
Source/com/drew/metadata/mp4/media/Mp4TextHandler.java
Source/com/drew/metadata/mp4/media/Mp4VideoHandler.java

These static fields were not threadsafe and create invalid data in concurrent environments.
There may be a better design for this, but for now these new context classes just move shared state to the stack.
Fixes #421.

Remove static state from MP4/QuickTime handlers

---

Source/com/drew/metadata/iptc/Iso2022Converter.java
Tests/com/drew/metadata/iptc/Iso2022ConverterTest.java

Fixes #437
Hey guys, we are using your framework in our company and face a situation where the encoding of our images can not be determined.
According to this page, the "1B 2E 41" which can be found in our "CodedCharacterSet" belongs to the ISO-8859-1 encoding.
http://nozer0.github.io/en/technology/system/character-encoding/

Added support of standard ISO-8859-1 encoding

---

build.gradle

This fixes unit tests on Windows due to encoding issues.
P.S. If you're interested, I created a Kotlin port over the weekend in my master branch which allows for even finer grained null safety and the removal of a lot of utility methods. Feel free to check it out if that sounds cool.

Fixes unit tests on Windows

---

Source/com/drew/imaging/FileTypeDetector.java
Source/com/drew/lang/ByteTrie.java

Fixes #449.
Fixes a bug where stream reading code would not loop if fewer than requested bytes were read, resulting in an array of zeroes being used for classification.
~Also adds an extra byte to the pattern used for MP3 detection.~

Improve file type detection

---

Source/com/drew/imaging/FileTypeDetector.java
Source/com/drew/imaging/TypeChecker.java
Source/com/drew/imaging/mp3/MpegAudioTypeChecker.java
Source/com/drew/imaging/quicktime/QuickTimeTypeChecker.java
Source/com/drew/imaging/riff/RiffTypeChecker.java

Relates to #328 and #450.
MP3 headers cannot be reliably detected using the prefix-tree approach. This PR ports part of drewnoakes/metadata-extractor-dotnet#233, which introduced an interface for custom type check logic.
It then uses that extension point to add enhanced MP3 detection.

Improve MP3 detection

---

Source/com/drew/metadata/exif/makernotes/CanonMakernoteDescriptor.java

Identified as a difference between Java and .NET outputs in:
https://github.com/drewnoakes/metadata-extractor-images/commit/f961c13f340eb9989ef5c991f307b26d805cb789

Improve Canon makernote quality description

---

Source/com/drew/metadata/Directory.java
Source/com/drew/metadata/mov/QuickTimeAtomHandler.java
Source/com/drew/metadata/mov/QuickTimeAtomTypes.java
Source/com/drew/metadata/mov/QuickTimeDirectory.java
Source/com/drew/metadata/mov/atoms/TrackHeaderAtom.java
Source/com/drew/metadata/mp4/Mp4BoxHandler.java
Source/com/drew/metadata/mp4/Mp4BoxTypes.java
Source/com/drew/metadata/mp4/Mp4Directory.java
Source/com/drew/metadata/mp4/boxes/UserDataBox.java

Hi Drew,
I did some improvements in the library:
- I found that timezone information gets lost when extracting metadata from some images, because the library expects it to be in `HH:mm` format, but actually it is in `HHmm`. 
- We needed to extract rotation angle from MOV files, so I implemented very basic handling of track headers.
Best regards,
Ferenc

Timezone parsing fix and mov rotation extraction

---

Source/com/drew/metadata/heif/boxes/ItemInfoBox.java

Hi Drew,
Very cool library you've made here.
I noticed that there were some silent IOExceptions being thrown when trying to extract metadata from some HEIF images I've taken.
My one comment explains what's happening pretty well. Essentially the ItemInfoBox was reading off the end of the bytes it was given because it was not taking into account that 8 bytes had already been read.
I thought I'd start small, I have another working branch that can actually pull EXIF data from HEIFs which shouldn't be impacted by the directory-per-image refactor mentioned in #445. I'll put that PR in after this one gets merged (First time contributing to open source, long time Java developer)

ItemInfoBox no longer throws exception when no content encoding is present

---

Source/com/drew/imaging/tiff/TiffReader.java
Source/com/drew/metadata/exif/makernotes/AppleMakernoteDirectory.java
Source/com/drew/metadata/heif/HeifItemTypes.java
Source/com/drew/metadata/heif/HeifPictureHandler.java
Source/com/drew/metadata/heif/boxes/ItemInfoBox.java
Source/com/drew/metadata/heif/boxes/ItemLocationBox.java

We now process the "mdat" container in HEIF images and handle any items in it that have the "Exif" type
We can see that Exif is successfully pulled out of all the HEIC images in metadata-extractor-images: https://github.com/drewnoakes/metadata-extractor-images/pull/36
NOTE: Doesn't work with the Nokia HEIF reference images because it seems that they don't follow the spec outlined in ISO/IEC 23008-12:2017 Annex A?

Extract Exif data from HEIF file types

---

Source/com/drew/imaging/png/PngChunkType.java
Source/com/drew/imaging/png/PngMetadataReader.java

By making use of the Tiff exif functionality, we can read the PNG exif information.
The following information was read from the file sampleWithExifData.png:
```
[Exif IFD0 - 0x8298] Copyright = Acme
[Exif IFD0 - 0x0131] Software = Acme-software: 1.0.0.0
[Exif IFD0 - 0x010e] Image Description = This is an image with exif data
[Exif SubIFD - 0x927c] Makernote = [33 values]
```

Read exif chunk from a PNG image

---

pom.xml

When including this library using Apache Ivy (for instance), `javac`  reports the following warning:
```
[javac] warning: [path] bad path element "/home/simon/.ivy2/cache/com.drewnoakes/metadata-extractor/jars/xmpcore-6.0.6.jar": no such file or directory
```
This is due to `Class-Path: xmpcore-6.0.6.jar` in `META-INF/MANIFEST.MF`
Ref: https://maven.apache.org/shared/maven-archiver/examples/classpath.html

Remove Class-Path entry from MANIFEST in jar

---

Source/com/drew/metadata/mov/atoms/TrackHeaderAtom.java

This breaks on Android.
Fixes #484.

Remove java.awt dependency

---

Source/com/drew/metadata/icc/IccDirectory.java

I believe the name of the ICC 'cprt' tag (0x63707274) would more accurately be described as the "Profile Copyright". It certainly isn't the copyright on the image which is what is implied by the unqualified name "Copyright".

Update name of the 'cprt' tag

---

Source/com/drew/imaging/FileType.java
Source/com/drew/imaging/quicktime/QuickTimeTypeChecker.java

This brings parity with the .NET implementation.
Closes #490.

Add CRX and other MP4/QuickTime file type detection

---

Source/com/drew/imaging/heif/HeifReader.java

I have not found any spec that says the 'meta' box has to be the first box in the file and we need the meta box to pick our handler.
When the meta box is the first box, we process like normal.
If the meta box is not the first box, we scan through the entire file and set the handler when we do find the meta box. Then we reset the stream (if we can) and process it with that new handler.
So this WILL break if the meta box is not the first AND the stream is not resettable...
Associated images PR: https://github.com/drewnoakes/metadata-extractor-images/pull/37
Resolves #487

Can now extract Exif from HEIF images where 'meta' is not the first box

---

Source/com/drew/metadata/exif/ExifTiffHandler.java

Fixes #539
This is a port of https://github.com/drewnoakes/metadata-extractor-dotnet/pull/298/
This fixes an issue where XMP data was not being extracted from some DJI images, and allows presentation of data such as:
```
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:AbsoluteAltitude = -30.037239
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:RelativeAltitude = 19.700001
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:GimbalRollDegree = 0.000000
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:GimbalYawDegree = 69.400002
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:GimbalPitchDegree = -60.000000
[XMPMeta - http://www.dji.com/drone-dji/1.0/] drone-dji:FlightRollDegree = -2.100000
[XMPMeta - http://www.dji.com/drone-dji/1.0/] …
```

Allow Application Notes (XMP) in SubIFD

---

Source/com/drew/imaging/tiff/TiffReader.java

Double64 should take 8 bytes, instead of 4. 
I found this bug when I tried to read tags from a geotiff.
The original data was 
7B 14 AE 47 E1 7A 84 3F  ----- 0.01  index 0 - 7 
7B 14 AE 47 E1 7A 84 3F  ----- 0.01  index 8 - 15 
00 00 00 00 00 00 00 00  ----- 0       index 16 - 23 
but metadata-extractor read it like this:
7B 14 AE 47 E1 7A 84 3F   ------- index 0 - 7
E1 7A 84 3F 7B 14 AE 47   ------- index 4 - 11 [should be 8 - 15]
7B 14 AE 47 E1 7A 84 3F   ------- index 8 - 15 [should be 16 - 23]

Fix reading arrays of Float64 in TIFF files

---

Source/com/drew/metadata/exif/ExifTiffHandler.java
Source/com/drew/metadata/exif/makernotes/ReconyxHyperFire2MakernoteDescriptor.java
Source/com/drew/metadata/exif/makernotes/ReconyxHyperFire2MakernoteDirectory.java

Adding support for Reconyx HyperFire 2 cameras.

Reconyx HyperFire 2 Support

---

Source/com/drew/lang/SequentialByteArrayReader.java
Source/com/drew/lang/StreamReader.java
Tests/com/drew/lang/SequentialAccessTestBase.java

An integer overflow can occur when extending the index, preventing
guard statements from catching indices outside the expected buffer
range and resulting in OutOfMemory exceptions from array allocation.

Fix integer addition overflow.

---

Source/com/drew/metadata/ico/IcoReader.java

According to the specs on https://docs.fileformat.com/image/ico/ a width/height of 0 means 256 for ico files.

In case of an ico file a height or with of 0 actually means 256

---

Source/com/drew/imaging/png/PngMetadataReader.java

This is a port of a fix from the .NET library in https://github.com/drewnoakes/metadata-extractor-dotnet/pull/329
PNG chunks of type `iTXt` should have keywords and values decoded using UTF-8, not Latin1 encoding.

Fix PNG iTXt encoding issue

---

Source/com/drew/imaging/png/PngMetadataReader.java
Source/com/drew/imaging/tiff/TiffMetadataReader.java
Source/com/drew/metadata/exif/ExifReader.java
Source/com/drew/metadata/exif/ExifThumbnailDescriptor.java
Source/com/drew/metadata/exif/ExifThumbnailDirectory.java
Source/com/drew/metadata/exif/ExifTiffHandler.java
Source/com/drew/metadata/photoshop/PhotoshopTiffHandler.java
Source/com/drew/metadata/tiff/DirectoryTiffHandler.java
Tests/com/drew/metadata/MetadataTest.java
Tests/com/drew/metadata/exif/ExifDirectoryTest.java
Tests/com/drew/metadata/exif/ExifThumbnailDescriptorTest.java

Fixes #578
The offset is currently reported relative to the start of the Exif data. However, most users will need the value relative to the start of the outermost data stream. This change attempts to provide that value.
Should work for JPEG and RAW files. Won't work for Exif data embedded within other formats such as PNG, QuickTime, WebP or HEIF. Such support could be added in future.

Fix Exif thumbnail offset

---

Source/com/drew/metadata/iptc/Iso2022Converter.java
Tests/com/drew/metadata/iptc/Iso2022ConverterTest.java

Fixes ##614
According to https://en.wikipedia.org/wiki/ISO/IEC_2022#cite_note-14.3.2-90 ISO-8859-1 should be used both when CodedCharacterSet is
ESC % A
ESC . A
ESC - A
Previously, only the first two syntaxes was supported.

Fix encoding problem when CodedCharacterSet is set to "ESC - A"

---

Source/com/drew/metadata/exif/makernotes/FujifilmMakernoteDescriptor.java
Source/com/drew/metadata/exif/makernotes/FujifilmMakernoteDirectory.java

This commit brings the following:
-  adds the ability to retrieve the image actuation for Fuji cameras
-  completes the list of Film simulations
-  turns method getMakerNoteVersionDescription from private to public
Nice work! Thank you!

Fujifilm enhancements

---

Source/com/drew/tools/ProcessAllImagesInFolderUtility.java

Running the test suite on a German OS causes all numbers to appear as "5,2" instead of "5.2", marking every file as diffs. Setting the global locale of java to en/US seems to resolve it.
Furthermore, due to a different timezone, creation+modifiy dates appear in different style

fix:set locale to en/us to format numbers with ".", not ","

---

Source/com/drew/metadata/StringValue.java

Using a different String constructor avoids needing an inner lookup, and avoids having to catch an exception.

Simplify string creation

---

Source/com/drew/metadata/exif/ExifTiffHandler.java

Added code to parse OM System II makernote (uses Olympus II makernote) by checking the signature in ProcessMakernote (matches andydragon/omsystem PR in metadata-extractor-dotnet and andydragon/omsystem PR in metadata-extractor-images)

Added code to parse OM System II makernote (uses Olympus II makernote)

---

README.md

As pointed out in #631, the README doesn't mention HEIF/HEIC support as it should.

Add HEIC/HEIF to README

---

Source/com/drew/metadata/Directory.java

Fixes the problem that parsing a date like `0000:00:00 00:00:00` will become `Sun Nov 30 00:00:00 GMT 2`.
Resolves #609.

Fixed parsing of illegal dates + handle known null value

---

Source/com/drew/imaging/FileType.java
Source/com/drew/imaging/ImageMetadataReader.java
Source/com/drew/imaging/quicktime/QuickTimeTypeChecker.java

The AVIF closely resembles the HEIF format, with the primary distinction lying in the compression algorithm applied to the pixel data. For extracting container metadata, one can employ the same logic, as AVIF utilizes the ISO BMFF boxes outlined in the HEIC standard.
Resolves #608.
Tested and verified using this sample file: [photo_74.avif.zip](https://github.com/drewnoakes/metadata-extractor/files/14151981/photo_74.avif.zip)

Support AVIF / AV1 images

---

Source/com/drew/metadata/Directory.java
Tests/com/drew/imaging/png/PngMetadataReaderTest.java
Tests/com/drew/metadata/DirectoryTest.java
Tests/com/drew/metadata/exif/ExifDirectoryTest.java
Tests/com/drew/metadata/icc/IccReaderTest.java

The code should not default back to GMT timezone, but instead assume that the image was taken in the same timezone as the computer is in. That should be true for most images.
The `PngMetadataReaderTest` had a pattern to deal with this. I expanded this to the other failing unit tests.
Fixes #628.

Fixed wrong date/time when timezone is null

---

Source/com/drew/metadata/jpeg/JpegReader.java

Allows for more precise error messages. Matches output of .NET library.

Validate lengths before parsing JPEG data

---

Source/com/drew/imaging/FileType.java
Tests/com/drew/imaging/FileTypeTest.java

Fix of #676

---

Source/com/drew/imaging/FileType.java
Source/com/drew/imaging/FileTypeDetector.java
Source/com/drew/imaging/ImageMetadataReader.java
Source/com/drew/metadata/TagDescriptor.java
Source/com/drew/tools/ProcessAllImagesInFolderUtility.java

Takes the same approach as the .NET library and optionally considered the file extension, when available, to disambiguate between some hard to identify files, such as camera raw files (which are mostly TIFF) and hard to identify from leading bytes.

Extend file type detection

---

Source/com/drew/metadata/exif/ExifTiffHandler.java
Source/com/drew/metadata/exif/makernotes/DjiMakernoteDescriptor.java
Source/com/drew/metadata/exif/makernotes/DjiMakernoteDirectory.java

- Ported from [drewnoakes/metadata-extractor](https://github.com/drewnoakes/metadata-extractor-dotnet/blob/main/MetadataExtractor/Formats/Exif/makernotes/DJIMakernoteDirectory.cs)'s .NET implementation
Fixes #698

Issue #698 | add DJI metadata support (ported from .NET)
