drewnoakes/metadata-extractor

.gitignore
Source/com/drew/metadata/Schema.java
Source/com/drew/metadata/xmp/XmpDirectory.java
Source/com/drew/metadata/xmp/XmpReader.java
Source/com/drew/metadata/xmp/XmpWriter.java
metadata-extractor.iml

Includes:
read, write, and modify of
'rating', 'label', 'subject' tags

Extended XMP support

---

Source/com/drew/metadata/jpeg/JpegComponent.java

swap sampling factor calcs

---

Source/com/drew/metadata/Directory.java
Source/com/drew/metadata/exif/ExifSubIFDDirectory.java
Tests/com/drew/metadata/DirectoryTest.java
Tests/com/drew/metadata/exif/ExifDirectoryTest.java

* Added the following new method with the subsecond parameter
* Directory.getDate(int tagType, String subsecond, TimeZone timeZone)
* Added the following new methods to get composite values from multiple tags
* ExifSubIFDDirectory.getDateOriginal()
* ExifSubIFDDirectory.getDateOriginal(TimeZone timeZone)
* ExifSubIFDDirectory.getDateDegitized()
* ExifSubIFDDirectory.getDateDegitized(TimeZone timeZone)
* Added a few date parsing tests

Added a new getDate() method with the subsecond parameter

---

Source/com/drew/metadata/xmp/XmpDirectory.java
Source/com/drew/metadata/xmp/XmpReader.java
Tests/com/drew/metadata/xmp/XmpReaderTest.java

* Added the following new Xmp tags
* XmpDirectory.TAG_BASE_URL
* XmpDirectory.TAG_CREATE_DATE
* XmpDirectory.TAG_CREATOR_TOOL
* XmpDirectory.TAG_IDENTIFIER
* XmpDirectory.TAG_METADATA_DATE
* XmpDirectory.TAG_MODIFY_DATE
* XmpDirectory.TAG_NICKNAME
* Added the following new method with a time zone parameter
* XmpDirectory.updateDate(int tagType, Date value, TimeZone timeZone)
* Added a few date parsing tests

Added XMP tags for properties in the XMP namespace

---

Source/com/drew/lang/Rational.java
Tests/com/drew/lang/RationalTest.java

Make Rational implement Comparable.

---

pom.xml

Upgrade xmpcore to 5.1.3, issue #188

Upgrade xmpcore to 5.1.3, issue #188

---

Source/com/drew/metadata/xmp/XmpReader.java

Implementation of the Extended XMP segments for the issue #184 .

Implemented Extended XMP decoding

---

Source/com/drew/metadata/gif/GifReader.java

I came across this while reading some of your code. I wasn't sure if I should create an issue or a PR for such a tiny thing, but I figured it's easier for you to just push merge/rebase on a PR 😉 
Thanks for a great library btw. 👍
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/drewnoakes/metadata-extractor/213)

Remove copy paste residue

---

Source/com/drew/metadata/gif/GifReader.java

Added error directory if unknown Gif blocks are found.

---

Source/com/drew/metadata/mov/metadata/QuickTimeMetadataDirectory.java

These tags were found on .mov files created by iPhone 7 Plus, iOS 10.2.1.

Add new tags to mov metadata.

---

Source/com/drew/metadata/mov/QuickTimeDirectory.java
Source/com/drew/metadata/mov/atoms/MovieHeaderAtom.java

Apply changes @qilab made to duration in mp4 directory ( #321 ) to the quicktime directory

Add a tag for duration in seconds to quicktime directory

---

Source/com/drew/metadata/TagDescriptor.java
Source/com/drew/metadata/exif/ExifDescriptorBase.java
Source/com/drew/metadata/exif/GpsDescriptor.java

This abstracts the code in `ExifDescriptorBase` and `GpsDescriptor` into a common method in `TagDescriptor`.

A common method for Exif encoded text descriptions

---

Source/com/drew/metadata/mp4/Mp4BoxHandler.java
Source/com/drew/metadata/mp4/Mp4BoxTypes.java
Source/com/drew/metadata/mp4/Mp4Directory.java
Source/com/drew/metadata/mp4/boxes/TrackHeaderBox.java

Fixes #348 
Uses [transformation matrix](https://developer.apple.com/library/content/documentation/QuickTime/RM/MovieBasics/MTEditing/K-Chapter/11MatrixFunctions.html) in track header box to calculate rotation angle.

Calculate rotation from track header box (tkhd)

---

Source/com/drew/metadata/mp4/media/Mp4MetaDirectory.java
Source/com/drew/metadata/mp4/media/Mp4MetaHandler.java
Source/com/drew/metadata/mp4/media/Mp4TextDirectory.java
Source/com/drew/metadata/mp4/media/Mp4TextHandler.java

Closes #368.
@payton if you're happy with these changes, please go ahead and merge the PR, or feel free to push your own changes to it. Thanks!

Fix some null pointer exceptions in MP4 code

---

Source/com/drew/metadata/heif/HeifBoxTypes.java
Source/com/drew/metadata/heif/HeifDescriptor.java
Source/com/drew/metadata/heif/HeifDirectory.java
Source/com/drew/metadata/heif/HeifPictureHandler.java
Source/com/drew/metadata/heif/boxes/ColourInformationBox.java
Source/com/drew/metadata/heif/boxes/ImageRotationBox.java
Source/com/drew/metadata/heif/boxes/PixelInformationBox.java

Adds Image Rotation Box ('irot'), Colour Information Box ('colr'), and Pixel Information Box ('pixi').
These will extract the following information:
* Image rotation (in degrees) counter-clockwise
* ICC Profile
* Bits per channel

HEIF Additions: irot, colr, pixi

---

build.gradle

upgrade com.adobe.xmp:xmpcore to 6.0.6, otherwise gradle building will fail.

fix build.gradle dependency issue

---

Source/com/drew/metadata/mp4/boxes/TrackHeaderBox.java

Due to java.lang.NoClassDefFoundError: java.awt.Point on Android

Removed java.awt.Point 

---

Source/com/drew/metadata/mov/QuickTimeMediaHandler.java
Source/com/drew/metadata/mov/atoms/MovieHeaderAtom.java
Source/com/drew/metadata/mp4/Mp4Directory.java
Source/com/drew/metadata/mp4/Mp4MediaHandler.java
Source/com/drew/metadata/mp4/boxes/MovieHeaderBox.java

This isn't a fully tested PR, think of it as a suggested fix. My very simple testing indicated that this fixes #408, but proper review/testing should be done.

Set Epoch to UTC in MP4 metadata

---

Source/com/drew/tools/ProcessAllImagesInFolderUtility.java

Part of https://github.com/drewnoakes/metadata-extractor-images/issues/20

Generate metadata files under a 'java' folder

---

Source/com/drew/lang/DateUtil.java
Source/com/drew/metadata/mov/QuickTimeMediaHandler.java
Source/com/drew/metadata/mov/atoms/MovieHeaderAtom.java
Source/com/drew/metadata/mp4/Mp4Directory.java
Source/com/drew/metadata/mp4/Mp4MediaHandler.java
Source/com/drew/metadata/mp4/boxes/MovieHeaderBox.java
metadata-extractor.iml

Moves epoch conversion code to `DateUtil` and other minor tweaks.
//cc: @Nadahar @payton @kwhopper

Refactor date processing

---

Source/com/drew/imaging/FileType.java
Source/com/drew/metadata/mp3/Mp3Directory.java
Source/com/drew/metadata/mp3/Mp3Reader.java
Source/com/drew/metadata/mp4/media/Mp4UuidBoxDirectory.java

While porting this to .NET, I cleaned a few things up.

Tweak MP3 code

---

Tests/com/drew/metadata/xmp/XmpReaderTest.java
pom.xml

Bump com.adobe.xmpcore to 6.1.11

---

Source/com/drew/metadata/Schema.java

Added Schema.PHOTOSHOP_PROPERTIES

---

Source/com/drew/lang/KeyValuePair.java

Added KeyValuePair.toString()

---

Source/com/drew/metadata/mp4/boxes/TrackHeaderBox.java

@drewnoakes Please find the proposed fix for issue: #532 
Fixes #532

fixing the MP4 rotation angle value

---

Source/com/drew/imaging/FileTypeDetector.java

Fixes #512. See discussion there for details.

Replace FilterInputStream with InputStream in FileTypeDetector

---

Source/com/drew/metadata/exif/ExifDirectoryBase.java

Added Exif 0x4749 (Rating Percent). See https://exiftool.org/TagNames/EXIF.html

Update ExifDirectoryBase.java. Added Exif 0x4749 (Rating Percent).

---

.github/workflows/maven.yml
README.md
build.gradle
pom.xml

We used to use Travis CI but that's no longer a viable option.

Set up GitHub actions for CI builds

---

Source/com/drew/imaging/png/PngMetadataReader.java
Source/com/drew/lang/SequentialReader.java
Source/com/drew/metadata/bmp/BmpReader.java
Source/com/drew/metadata/exif/makernotes/NikonPictureControl2Directory.java
Source/com/drew/metadata/heif/boxes/HandlerBox.java
Source/com/drew/metadata/heif/boxes/ItemInfoBox.java
Source/com/drew/metadata/mp4/Mp4BoxHandler.java
Tests/com/drew/lang/SequentialAccessTestBase.java

A port of behaviour from the .NET library.

Trim trailing null bytes from some string values

---

.github/workflows/maven.yml
build.gradle
metadata-extractor.iml
pom.xml

Bump Java version to 1.8

---

Source/com/drew/metadata/TagDescriptor.java

Raised in drewnoakes/metadata-extractor-dotnet#352

Fix rounding error in shutter speed description
